export enum LoanType {
    ASSET_FINANCE = 'ASSET_FINANCE',
    COMMERCIAL = 'COMMERCIAL',
    INSURANCE = 'INSURANCE',
    PERSONAL = 'PERSONAL',
    RESIDENTIAL = 'RESIDENTIAL',
    RISK_INSURANCE = 'RISK_INSURANCE',
    OTHER = 'OTHER',
}
