export enum PropertyType {
    CONSTRUCTION = 'CONSTRUCTION',
    ESTABLISHED_PROPERTY = 'ESTABLISHED_PROPERTY',
    LAND_AND_CONSTRUCTION = 'LAND_AND_CONSTRUCTION',
    NEW_BUILDING = 'NEW_BUILDING',
    VACANT_LAND = 'VACANT_LAND',
}
